In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
# Naive biased implementation

In [17]:
from sklearn.datasets  import load_iris

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X,y = load_iris(return_X_y=True)

In [20]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 0)

In [22]:
from sklearn.naive_bayes import GaussianNB

In [23]:
gnb = GaussianNB()

In [24]:
gnb.fit(X_train,y_train)


GaussianNB()

In [25]:
y_pred = gnb.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [27]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [29]:
tips = sns.load_dataset('tips')


In [30]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [54]:
from sklearn.preprocessing import LabelEncoder

In [86]:
X=tips[[ 'sex', 'time', 'size']]
y=tips['smoker']

In [87]:
##train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [88]:
gnb = GaussianNB()

In [89]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [90]:
import warnings
warnings.filterwarnings('ignore')
X_train['sex']=le1.fit_transform(X_train['sex'])
# X_train['total_bill']=le2.fit_transform(X_train['total_bill'])
X_train['time']=le3.fit_transform(X_train['time'])

In [91]:
X_test['sex']=le1.transform(X_test['sex'])
# X_test['total_bill']=le2.transform(X_test['total_bill'])
X_test['time']=le3.transform(X_test['time'])

In [92]:
y_train = le2.fit_transform(y_train)

In [93]:
y_test = le2.transform(y_test)

In [94]:
X_test

sex  time  size
162    0     0     3
60     1     0     2
61     1     0     2
63     1     0     4
69     1     0     2
..   ...   ...   ...
201    0     1     2
149    1     1     2
175    1     0     2
226    0     1     2
49     1     0     2

[61 rows x 3 columns]

In [95]:
gnb.fit(X_train,y_train)

GaussianNB()

In [96]:
y_pred = gnb.predict(X_test)

In [99]:
y_pred

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1])

In [100]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[21 19]
 [12  9]]
0.4918032786885246
              precision    recall  f1-score   support

           0       0.64      0.53      0.58        40
           1       0.32      0.43      0.37        21

    accuracy                           0.49        61
   macro avg       0.48      0.48      0.47        61
weighted avg       0.53      0.49      0.50        61

